# Generated by Django 2.1.2 on 2018-11-06 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181030_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.TextField(default='Admin', max_length=25),
        ),
        migrations.AddField(
            model_name='posts',
            name='tags',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
